export default [
  { amount: 10, commandName: `advice`, title: `leveling/missions:ADVICE`, reward: 30 },
  { amount: 3, commandName: `afk`, title: `leveling/missions:AFK`, reward: 30 },
  { amount: 5, commandName: `background`, title: `leveling/missions:BACKGROUND`, reward: 50 },
  { amount: 5, commandName: `baka`, title: `leveling/missions:BAKA`, reward: 50 },
  { amount: 1, commandName: `bugs`, title: `leveling/missions:BUGS`, reward: 10 },
  { amount: 5, commandName: `compliment`, title: `leveling/missions:COMPLIMENT`, reward: 50 },
  { amount: 5, commandName: `hug`, title: `leveling/missions:HUG`, reward: 50 },
  { amount: 1, commandName: `idea`, title: `leveling/missions:IDEA`, reward: 10 },
  { amount: 5, commandName: `profile`, title: `leveling/missions:PROFILE`, reward: 150 },
  { amount: 3, commandName: `role`, title: `leveling/missions:ROLE`, reward: 30 },
  { amount: 5, commandName: `user`, title: `leveling/missions:USER`, reward: 70 },
  { amount: 10, commandName: `wisdom`, title: `leveling/missions:WISDOM`, reward: 30 },
  { amount: 3, commandName: `votefeedback`, title: `leveling/missions:VOTEFEEDBACK`, reward: 10 },
  { amount: 1, commandName: `voice10min`, title: `leveling/missions:VOICE10MIN`, reward: 50 },
  { amount: 1, commandName: `avatar`, title: `leveling/missions:AVATAR`, reward: 5 },
  { amount: 3, commandName: `cuddle`, title: `leveling/missions:CUDDLE`, reward: 15 },
  { amount: 5, commandName: `kiss`, title: `leveling/missions:KISS`, reward: 30 },
  { amount: 5, commandName: `poke`, title: `leveling/missions:POKE`, reward: 10 },
  { amount: 5, commandName: `tickle`, title: `leveling/missions:TICKLE`, reward: 10 },
  { amount: 1, commandName: `guildadded`, title: `leveling/missions:GUILDADDED`, reward: 200 }
]
