export default [
  { name: `Airi`, image: `https://i.imgur.com/n6ZvXrX.jpg` },
  { name: `Aleister`, image: `https://i.imgur.com/zeJUccQ.jpg` },
  { name: `Alice`, image: `https://i.imgur.com/dnAnzGi.jpg` },
  { name: `Amily`, image: `https://i.imgur.com/kSeoFDa.jpg` },
  { name: `Annette`, image: `https://i.imgur.com/fUq1QeB.png` },
  { name: `Arduin`, image: `https://i.imgur.com/8rwQI9H.jpg` },
  { name: `Arthur`, image: `https://i.imgur.com/Hrx4IzS.jpg` },
  { name: `Arum`, image: `https://i.imgur.com/g8PPHxQ.jpg` },
  { name: `Astrid`, image: `https://i.imgur.com/UsQFVER.jpg` },
  { name: `Azzen'Ka`, image: `https://i.imgur.com/ZuegiK9.jpg` },
  { name: `Baldum`, image: `https://i.imgur.com/ARSC5r9.jpg` },
  { name: `Butterfly`, image: `https://i.imgur.com/c1OjmwD.jpg` },
  { name: `Chaugnar`, image: `https://i.imgur.com/2x4R90r.jpg` },
  { name: `Cresht`, image: `https://i.imgur.com/1PMu2nh.jpg` },
  { name: `D'Arcy`, image: `https://i.imgur.com/MajddzV.png` },
  { name: `Diaochan`, image: `https://i.imgur.com/u7KhQre.jpg` },
  { name: `Elsu`, image: `https://i.imgur.com/iota44K.jpg` },
  { name: `Errol`, image: `https://i.imgur.com/ByfYifV.jpg` },
  { name: `Fennik`, image: `https://i.imgur.com/GE6wsv6.jpg` },
  { name: `Florentino`, image: `https://i.imgur.com/kB4Zea4.jpg` },
  { name: `Gildur`, image: `https://i.imgur.com/Z24UK4y.jpg` },
  { name: `Grakk`, image: `https://i.imgur.com/pa8xa4U.jpg` },
  { name: `Hayate`, image: `https://i.imgur.com/ITwj80k.jpg` },
  { name: `Ignis`, image: `https://i.imgur.com/0wR0pjs.jpg` },
  { name: `Ilumia`, image: `https://i.imgur.com/nGAmSmD.jpg` },
  { name: `Jinnar`, image: `https://i.imgur.com/5EfClzT.png` },
  { name: `Joker`, image: `https://i.imgur.com/q5tskwI.jpg` },
  { name: `Kahlii`, image: `https://i.imgur.com/6m4nEOd.jpg` },
  { name: `Kil'Groth`, image: `https://i.imgur.com/HEUajpd.jpg` },
  { name: `Kriknak`, image: `https://i.imgur.com/OqrWcG4.jpg` },
  { name: `Krixi`, image: `https://i.imgur.com/UZjyLsY.jpg` },
  { name: `Lauriel`, image: `https://i.imgur.com/H56zYGe.jpg` },
  { name: `Liliana`, image: `https://i.imgur.com/ArjU81y.jpg` },
  { name: `Lindis`, image: `https://i.imgur.com/vPihyfl.jpg` },
  { name: `Lu Bu`, image: `https://i.imgur.com/3MArDPK.jpg` },
  { name: `Lumburr`, image: `https://i.imgur.com/3p0Jaok.jpg` },
  { name: `Maloch`, image: `https://i.imgur.com/BvXPBNs.jpg` },
  { name: `Marja`, image: `https://i.imgur.com/xppJb1X.jpg` },
  { name: `Max`, image: `https://i.imgur.com/f2SSIXM.png` },
  { name: `Mganga`, image: `https://i.imgur.com/6ZyHM97.jpg` },
  { name: `Mina`, image: `https://i.imgur.com/fyvFYeN.jpg` },
  { name: `Moren`, image: `https://i.imgur.com/LtI0mPc.jpg` },
  { name: `Murad`, image: `https://i.imgur.com/0Iia6IH.jpg` },
  { name: `Nakroth`, image: `https://i.imgur.com/Vx94ZCH.jpg` },
  { name: `Natalya`, image: `https://i.imgur.com/TgQrrEb.jpg` },
  { name: `Omega`, image: `https://i.imgur.com/W7Hn44i.jpg` },
  { name: `Omen`, image: `https://i.imgur.com/j328PK8.jpg` },
  { name: `Ormarr`, image: `https://i.imgur.com/jSJ3ft6.jpg` },
  { name: `Peura`, image: `https://i.imgur.com/LN7J744.jpg` },
  { name: `Preyta`, image: `https://i.imgur.com/5iv3qIN.jpg` },
  { name: `Quillen`, image: `https://i.imgur.com/upiqSKi.jpg` },
  { name: `Raz`, image: `https://i.imgur.com/p5CKSq8.jpg` },
  { name: `Riktor`, image: `https://i.imgur.com/UbMMn1N.jpg` },
  { name: `Rourke`, image: `https://i.imgur.com/9ta7okC.jpg` },
  { name: `Roxie`, image: `https://i.imgur.com/uMDMfTK.jpg` },
  { name: `Ryoma`, image: `https://i.imgur.com/ShV2u8b.jpg` },
  { name: `Sephera`, image: `https://i.imgur.com/8wyM3iK.png` },
  { name: `Skud`, image: `https://i.imgur.com/mqbtXfX.jpg` },
  { name: `Slimz`, image: `https://i.imgur.com/HZi9SNU.jpg` },
  { name: `Superman`, image: `https://i.imgur.com/OPmtn5N.png` },
  { name: `Taara`, image: `https://i.imgur.com/NrAGKu1.jpg` },
  { name: `TeeMee`, image: `https://i.imgur.com/cPdnCTA.jpg` },
  { name: `Tel'Annas`, image: `https://i.imgur.com/X1yCtkh.jpg` },
  { name: `Thane`, image: `https://i.imgur.com/1jJXA5I.jpg` },
  { name: `The Flash`, image: `https://i.imgur.com/glulM2R.png` },
  { name: `Toro`, image: `https://i.imgur.com/qoXGsJN.png` },
  { name: `Tulen`, image: `https://i.imgur.com/NrAGKu1.jpg` },
  { name: `Valhein`, image: `https://i.imgur.com/mUGDTJ6.jpg` },
  { name: `Veera`, image: `https://i.imgur.com/s0dGCl0.jpg` },
  { name: `Veres`, image: `https://i.imgur.com/uKJ5r3T.jpg` },
  { name: `Violet`, image: `https://i.imgur.com/yQJwcHI.jpg` },
  { name: `Wiro`, image: `https://i.imgur.com/91Z0Ww4.jpg` },
  { name: `Wisp`, image: `https://i.imgur.com/6HigNXz.jpg` },
  { name: `Wukong`, image: `https://i.imgur.com/yLCCnai.jpg` },
  { name: `Xeniel`, image: `https://i.imgur.com/lKzZCOM.jpg` },
  { name: `Y'Bneth`, image: `https://i.imgur.com/MP5khtR.jpg` },
  { name: `Yorn`, image: `https://i.imgur.com/2pKBDC1.jpg` },
  { name: `Zanis`, image: `https://i.imgur.com/9m3JYah.jpg` },
  { name: `Zephys`, image: `https://i.imgur.com/GakyJBK.jpg` },
  { name: `Zill`, image: `https://i.imgur.com/5xtR4KA.jpg` },
  { name: `Zuka`, image: `https://i.imgur.com/pow4fzH.jpg` },
  { name: `Boomstick`, image: `https://i.imgur.com/7o5GU44.png` },
  { name: `Apocalypse`, image: `https://i.imgur.com/9q0lUCK.png` },
  { name: `Magic Ring`, image: `https://i.imgur.com/vImP6Q6.png` },
  { name: `Ancient Scriptures`, image: `https://i.imgur.com/yJMdRf0.png` },
  { name: `Trick Blade`, image: `https://i.imgur.com/YnbQKqd.png` },
  { name: `Beriths agony`, image: `https://i.imgur.com/ppVygLp.png` },
  { name: `Holy Of Holies`, image: `https://i.imgur.com/oXRMfAH.png` },
  { name: `Lapis Ring`, image: `https://i.imgur.com/eiA3B2F.png` },
  { name: `Spell Tome`, image: `https://i.imgur.com/T2D6tlz.png` },
  { name: `Frosty's Revenge`, image: `https://i.imgur.com/zzcPW6s.png` },
  { name: `Soaring Aura`, image: `https://i.imgur.com/2Hyabae.png` },
  { name: `Virtues's Necklace`, image: `https://i.imgur.com/DSRdHiL.png` },
  { name: `Zweihander`, image: `https://i.imgur.com/9m1sOfM.png` },
  { name: `Vlad's Impaler`, image: `https://i.imgur.com/cxAEsOR.png` },
  { name: `Tomb Of The Reaper`, image: `https://i.imgur.com/swfRZrJ.png` },
  { name: `Enchanted Scroll`, image: `https://i.imgur.com/WWLV87T.png` },
  { name: `Pendant Of Faith`, image: `https://i.imgur.com/ZRWFcIl.png` },
  { name: `Phoenix Tear`, image: `https://i.imgur.com/4dkksep.png` },
  { name: `Rhea's Blessing`, image: `https://i.imgur.com/XX6NHHu.png` },
  { name: `Spoopy Mask`, image: `https://i.imgur.com/wAdwilz.png` },
  { name: `Orb Of The Magi`, image: `https://i.imgur.com/nBgZjWu.png` },
  { name: `Hecate's Diadem`, image: `https://i.imgur.com/dYfX6IP.png` },
  { name: `Virtue's Bracelet`, image: `https://i.imgur.com/EVHpZuH.png` },
  { name: `Staff Of Nuul`, image: `https://i.imgur.com/abn3g7X.png` },
  { name: `Gilded Greaves`, image: `https://i.imgur.com/KSvUaGN.png` },
  { name: `Hermes Select`, image: `https://i.imgur.com/YI1hYpT.png` },
  { name: `Flashy Boots`, image: `https://i.imgur.com/0Bd8kxV.png` },
  { name: `Sonic Boots`, image: `https://i.imgur.com/YClkjLy.png` },
  { name: `Boots Of Speed`, image: `https://i.imgur.com/QxaS6dm.png` },
  { name: `War Boots`, image: `https://i.imgur.com/pzZPUnA.png` },
  { name: `Enchanted Kicks`, image: `https://i.imgur.com/I3RFQSY.png` },
  { name: `Whispering Wind`, image: `https://i.imgur.com/IyOUXBx.png` },
  { name: `Hunter’s Crossbow`, image: `https://i.imgur.com/mLVoG5R.png` },
  { name: `Monsters Bane`, image: `https://i.imgur.com/DaUVWRH.png` },
  { name: `Mr Stabby`, image: `https://i.imgur.com/5gIgfia.png` },
  { name: `Gnoll Cleaver`, image: `https://i.imgur.com/Y42dlm3.png` },
  { name: `Leviathan`, image: `https://i.imgur.com/YDtlvvd.png` },
  { name: `Loki’s Curse`, image: `https://i.imgur.com/FiIEnnV.png` },
  { name: `Scorching Wind`, image: `https://i.imgur.com/r5zjkCq.png` },
  { name: `Arcane Hammer`, image: `https://i.imgur.com/cjNaVFV.png` },
  { name: `Astral Spear`, image: `https://i.imgur.com/svXyJTq.png` },
  { name: `Blitz Blade`, image: `https://i.imgur.com/DTWhW35.png` },
  { name: `Bloodied Club`, image: `https://i.imgur.com/t5z7LPX.png` },
  { name: `Chainhammer`, image: `https://i.imgur.com/addHDgr.png` },
  { name: `Claves Sancti`, image: `https://i.imgur.com/XIm5sBI.png` },
  { name: `Cleaving Claymore`, image: `https://i.imgur.com/qeceMkv.png` },
  { name: `Curse Of Death`, image: `https://i.imgur.com/llky2OD.png` },
  { name: `Short Sword`, image: `https://i.imgur.com/8KaHjFj.png` },
  { name: `Dagger`, image: `https://i.imgur.com/hbfJasL.png` },
  { name: `Death Sickle`, image: `https://i.imgur.com/p8ajaJ3.png` },
  { name: `Devil's Handshake`, image: `https://i.imgur.com/5KGtDYO.png` },
  { name: `Fafnir's Talon`, image: `https://i.imgur.com/og2VgQm.png` },
  { name: `Fafnir's Tooth`, image: `https://i.imgur.com/NhFFRA8.png` },
  { name: `Gloves`, image: `https://i.imgur.com/zV2CJuN.png` },
  { name: `Muramasa`, image: `https://i.imgur.com/t9RbcYz.png` },
  { name: `Omni Arms`, image: `https://i.imgur.com/1O6ktng.png` },
  { name: `Rank Breaker`, image: `https://i.imgur.com/fH39tgX.png` },
  { name: `Short Sword`, image: `https://i.imgur.com/8KaHjFj.png` },
  { name: `Shuriken`, image: `https://i.imgur.com/3fBI8zx.png` },
  { name: `Slick's Sting`, image: `https://i.imgur.com/H5wEPC7.png` },
  { name: `Spear Of Longinus`, image: `https://i.imgur.com/btMBYnA.png` },
  { name: `Tempest Blades`, image: `https://i.imgur.com/wCCXIp4.png` },
  { name: `The Beast`, image: `https://i.imgur.com/wCCXIp4.png` },
  { name: `Uriel's Brand`, image: `https://i.imgur.com/VGmA7XZ.png` },
  { name: `Amulet Of Longetivity`, image: `https://i.imgur.com/wQ0HKaX.png` },
  { name: `Acenstral Glory`, image: `https://i.imgur.com/Ni4mlBd.png` },
  { name: `Asterion's Buckler`, image: `https://i.imgur.com/E0k5Bvh.png` },
  { name: `Belt Of Clarity`, image: `https://i.imgur.com/8fYFQUc.png` },
  { name: `Crimson Banner`, image: `https://i.imgur.com/fMasN8X.png` },
  { name: `Frost Cape`, image: `https://i.imgur.com/Tc5q0aS.png` },
  { name: `Gaia's Standard`, image: `https://i.imgur.com/ILV5f1q.png` },
  { name: `Gladiator's Gauntlets`, image: `https://i.imgur.com/FQaNgaa.png` },
  { name: `Greaves Of Protection`, image: `https://i.imgur.com/aSAGCzO.png` },
  { name: `Heart Of Incubus`, image: `https://i.imgur.com/eUsGBk6.png` },
  { name: `Hercules Madness`, image: `https://i.imgur.com/bVfVqWd.png` },
  { name: `Hyoga's Edge`, image: `https://i.imgur.com/LWxblPs.png` },
  { name: `Knight's Plate`, image: `https://i.imgur.com/c9Cuarr.png` },
  { name: `Light Armor`, image: `https://i.imgur.com/0CrPKH5.png` },
  { name: `Mail Of Pain`, image: `https://i.imgur.com/Iei7nas.png` },
  { name: `Mantle Of Ra`, image: `https://i.imgur.com/i4dLfzV.png` },
  { name: `Medallion Of Troy`, image: `https://i.imgur.com/maxHXQV.png` },
  { name: `Necklace Of Vitality`, image: `https://i.imgur.com/XJRZdHp.png` },
  { name: `Odin's Will`, image: `https://i.imgur.com/GTnvfvm.png` },
  { name: `Platinum Gauntlets`, image: `https://i.imgur.com/WvLo5AN.png` },
  { name: `Ring Of Vitality`, image: `https://i.imgur.com/0xriIJC.png` },
  { name: `Rock Shield`, image: `https://i.imgur.com/TEODyhr.png` },
  { name: `Shield Of The Lost`, image: `https://i.imgur.com/7Dxkem7.png` },
  { name: `Talisman Of Strength`, image: `https://i.imgur.com/GqoVbns.png` },
  { name: `The Aegis`, image: `https://i.imgur.com/0pbCVsR.png` },
  { name: `Purifying Bracers`, image: `https://i.imgur.com/wCcJYYC.png` },
  { name: `Ring Of The Fiend`, image: `https://i.imgur.com/ExSjn0K.png` },
  { name: `Tidecaller's Mark`, image: `https://i.imgur.com/PNgpopE.png` },
  { name: `Essence Of The Wind`, image: `https://i.imgur.com/r8nqqwi.png` }
]
